'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageBid
    
    '''<summary>
    '''MerchantDetailsView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MerchantDetailsView As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''MerchantDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MerchantDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''FarmerDetailsView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FarmerDetailsView As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''FarmerDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FarmerDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
